services:
  - type: web
    name: pokerbot-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn make_episode:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: ELEVEN_API_KEY
        sync: false
      - key: VOICE_ID
        value: Adam